<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SriOff" failures="3" tests="4" name="Test" time="26.678" errors="0" timestamp="10 Jun 2021 17:58:55 GMT">
  <testcase classname="com.amz.qa.testcases.RestAPI" name="DeleteEmployee" time="8.925">
    <failure type="java.lang.AssertionError" message="expected [&amp;quot;message&amp;quot;:&amp;quot;Successfully! Record has been deleted&amp;quot;] but found [io.restassured.internal.RestAssuredResponseImpl@255eaa6b]">
      <![CDATA[java.lang.AssertionError: expected ["message":"Successfully! Record has been deleted"] but found [io.restassured.internal.RestAssuredResponseImpl@255eaa6b]
at com.amz.qa.testcases.RestAPI.DeleteEmployee(RestAPI.java:57)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- DeleteEmployee -->
  <testcase classname="com.amz.qa.testcases.RestAPI" name="GetAllEmployees" time="2.862">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.amz.qa.testcases.RestAPI.GetAllEmployees(RestAPI.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- GetAllEmployees -->
  <testcase classname="com.amz.qa.testcases.RestAPI" name="GetEmployee" time="1.302">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at com.amz.qa.testcases.RestAPI.GetEmployee(RestAPI.java:37)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- GetEmployee -->
  <testcase classname="com.amz.qa.testcases.AmzonTest" name="searchResults" time="8.764"/>
</testsuite> <!-- Test -->
